"""removed duplicate created_at from LinkedinPost

Revision ID: 55f99b29f9c6
Revises: 984fd6ede51c
Create Date: 2025-08-30 15:41:01.586155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55f99b29f9c6'
down_revision: Union[str, Sequence[str], None] = '984fd6ede51c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('linkedin_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('linkedin_post', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###
