"""add linkedin_post table

Revision ID: 5ca38e6b4f5a
Revises: 55f99b29f9c6
Create Date: 2026-08-08 16:26:45.680155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ca38e6b4f5a'
down_revision: Union[str, Sequence[str], None] = '55f99b29f9c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if 'linkedin_post' not in inspector.get_table_names():
        op.create_table('linkedin_post',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('text', sa.Text(), nullable=True),
        sa.Column('screenshot_path', sa.String(length=500), nullable=True),
        sa.Column('url', sa.Text(), nullable=True),
        sa.Column('processed', sa.Boolean(), nullable=False),
        sa.Column('deleted', sa.Boolean(), nullable=False),
        sa.Column('vacancy_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['vacancy_id'], ['vacancy.id'], ),
        sa.PrimaryKeyConstraint('id')
        )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('linkedin_post')
    # ### end Alembic commands ###
