"""added summary for resume

Revision ID: a7d729fc376e
Revises: afa84864b87f
Create Date: 2025-07-01 20:24:14.147080

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a7d729fc376e"
down_revision: str | Sequence[str] | None = "afa84864b87f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resume", schema=None) as batch_op:
        batch_op.add_column(sa.Column("summary", sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resume", schema=None) as batch_op:
        batch_op.drop_column("summary")

    # ### end Alembic commands ###
