"""Make email resume_path nullable.

Revision ID: c41f620767fd
Revises: fd2864f52d45
Create Date: 2025-07-18 08:40:27.618546

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'c41f620767fd'
down_revision: str | Sequence[str] | None = 'fd2864f52d45'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
