"""vacancy ID for LinkedinPosts is optional now

Revision ID: c52bfebb9fb5
Revises: ef82f8b78416
Create Date: 2025-06-28 11:01:10.924695

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c52bfebb9fb5"
down_revision: str | Sequence[str] | None = "ef82f8b78416"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("linkedin_post", schema=None) as batch_op:
        batch_op.alter_column("vacancy_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("linkedin_post", schema=None) as batch_op:
        batch_op.alter_column("vacancy_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
