"""fixed vacancy - to - linkedin post connection.

Revision ID: fd2864f52d45
Revises: fe64769958af
Create Date: 2025-07-18 07:54:25.444535

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'fd2864f52d45'
down_revision: str | Sequence[str] | None = 'fe64769958af'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
