"""created created_at fields and added url for vacancy

Revision ID: fe64769958af
Revises: da0fe57b5ac9
Create Date: 2025-07-17 12:14:14.864153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe64769958af'
down_revision: Union[str, Sequence[str], None] = 'da0fe57b5ac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basic_evaluation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    with op.batch_alter_table('vacancy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_vacancy")
    with op.batch_alter_table('vacancy', schema=None) as batch_op:
        batch_op.drop_column('url')

    op.execute("DROP TABLE IF EXISTS _alembic_tmp_resume")
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    op.execute("DROP TABLE IF EXISTS _alembic_tmp_email")
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    op.execute("DROP TABLE IF EXISTS _alembic_tmp_basic_evaluation")
    with op.batch_alter_table('basic_evaluation', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
