services:
  cloak-browser:
    image: cloakhq/cloakbrowser:latest
    container_name: cloak-browser-dev
    security_opt:
      - seccomp:unconfined
    ports:
      - "9222:9222"
    volumes:
      - ./resources:/app/resources
    networks:
      - ljpa-network

networks:
  ljpa-network:
    driver: bridge
